### ISSUE TITLE
个别词汇会引起程序阻塞甚至卡死

### ISSUE THREAD

**Issue by NeptuneNeptune** [rnkrsoft/Bopomofo4j#4]
使用版本 1.0.0
无意中发现的问题，同事在转换“众行通”或者“众行”两个词汇的时候，程序直接长时间阻塞或者说卡死了。
具体代码我没看过，也不清楚是否还会有其他的词汇会造成这种现象。
这样的情况对程序的影响非常大，希望能修复一下。
祝你们越弄越好，加油！

**Comment by NeptuneNeptune** [comment]
简单跟了一下代码，发现在一个叫做pinyins的方法里陷入了死循环，怀疑是逻辑上有错误。

**Comment by MrSorrow** [comment]
> 简单跟了一下代码，发现在一个叫做pinyins的方法里陷入了死循环，怀疑是逻辑上有错误。

有进展吗，issue列表的前两个问题都遇到了，感觉这个用起来很不放心:(

**Comment by rnkrsoft** [comment]
能详细说说什么情况吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [rnkrsoft/Bopomofo4j] 个别词汇会引起程序阻塞甚至卡死 (#4)




  
简单跟了一下代码，发现在一个叫做pinyins的方法里陷入了死循环，怀疑是逻辑上有错误。
  
有进展吗，issue列表的前两个问题都遇到了，感觉这个用起来很不放心:(

**Comment by rnkrsoft** [comment]
已修复
